In [14]:
import pandas as pd
import numpy as np

In [26]:
rental_listings = pd.read_csv('data/housing_train.csv')
print(rental_listings.shape)

(265190, 22)


In [27]:
rental_listings.head()

id                                                url      region  \
0  7039061606  https://bham.craigslist.org/apa/d/birmingham-h...  birmingham   
1  7041970863  https://bham.craigslist.org/apa/d/birmingham-w...  birmingham   
2  7041966914  https://bham.craigslist.org/apa/d/birmingham-g...  birmingham   
3  7041966936  https://bham.craigslist.org/apa/d/birmingham-f...  birmingham   
4  7041966888  https://bham.craigslist.org/apa/d/birmingham-2...  birmingham   

                    region_url  price       type  sqfeet  beds  baths  \
0  https://bham.craigslist.org   1195  apartment    1908     3    2.0   
1  https://bham.craigslist.org   1120  apartment    1319     3    2.0   
2  https://bham.craigslist.org    825  apartment    1133     1    1.5   
3  https://bham.craigslist.org    800  apartment     927     1    1.0   
4  https://bham.craigslist.org    785  apartment    1047     2    1.0   

   cats_allowed  ...  wheelchair_access  electric_vehicle_charge  \
0             1  ...                  0                        0   
1             1  ...                  0                        0   
2             1  ...                  0                        0   
3             1  ...                  0                        0   
4             1  ...                  0                        0   

   comes_furnished  laundry_options     parking_options  \
0                0  laundry on site      street parking   
1                0  laundry on site  off-street parking   
2                0  laundry on site      street parking   
3                0  laundry on site      street parking   
4                0  laundry on site      street parking   

                                           image_url  \
0  https://images.craigslist.org/00L0L_80pNkyDeG0...   
1  https://images.craigslist.org/00707_uRrY9CsNMC...   
2  https://images.craigslist.org/00h0h_b7Bdj1NLBi...   
3  https://images.craigslist.org/00808_6ghZ8tSRQs...   
4  https://images.craigslist.org/00y0y_21c0FOvUXm...   

                                         description      lat     long  state  
0  Apartments In Birmingham AL Welcome to 100 Inv...  33.4226 -86.7065     al  
1  Find Your Way to Haven Apartment Homes Come ho...  33.3755 -86.8045     al  
2  Apartments In Birmingham AL Welcome to 100 Inv...  33.4226 -86.7065     al  
3  Apartments In Birmingham AL Welcome to 100 Inv...  33.4226 -86.7065     al  
4  Apartments In Birmingham AL Welcome to 100 Inv...  33.4226 -86.7065     al  

[5 rows x 22 columns]

In [28]:
# Dropping unnecessary columns
rental_listings.drop(['url', 'region_url', 'image_url', 'description', 'lat', 'long', 'state'], axis = 1, inplace = True) 

# For now dropping Description column, but later we will consider this feature as it has a lot of 
# information related to location and proximity

In [29]:
print(rental_listings.shape)

(265190, 15)


In [30]:
rental_listings.head(10)

id      region  price       type  sqfeet  beds  baths  \
0  7039061606  birmingham   1195  apartment    1908     3    2.0   
1  7041970863  birmingham   1120  apartment    1319     3    2.0   
2  7041966914  birmingham    825  apartment    1133     1    1.5   
3  7041966936  birmingham    800  apartment     927     1    1.0   
4  7041966888  birmingham    785  apartment    1047     2    1.0   
5  7041966868  birmingham    900  apartment    1298     2    2.0   
6  7041966702  birmingham    925  apartment    1350     2    2.0   
7  7041964186  birmingham   1085      house    2308     3    2.0   
8  7041960353  birmingham   1269  apartment    1156     3    2.0   
9  7041959413  birmingham    799  apartment     703     1    1.0   

   cats_allowed  dogs_allowed  smoking_allowed  wheelchair_access  \
0             1             1                1                  0   
1             1             1                1                  0   
2             1             1                1                  0   
3             1             1                1                  0   
4             1             1                1                  0   
5             1             1                1                  0   
6             1             1                1                  0   
7             1             1                0                  0   
8             1             1                1                  0   
9             1             1                1                  0   

   electric_vehicle_charge  comes_furnished  laundry_options  \
0                        0                0  laundry on site   
1                        0                0  laundry on site   
2                        0                0  laundry on site   
3                        0                0  laundry on site   
4                        0                0  laundry on site   
5                        0                0  laundry on site   
6                        0                0  laundry on site   
7                        0                0      w/d hookups   
8                        0                0      w/d in unit   
9                        0                0      w/d in unit   

      parking_options  
0      street parking  
1  off-street parking  
2      street parking  
3      street parking  
4      street parking  
5      street parking  
6      street parking  
7                 NaN  
8                 NaN  
9                 NaN

In [31]:
# On the basis of description, we will give some score

In [35]:
rental_listings.type.unique()

array(['apartment', 'house', 'manufactured', 'townhouse', 'condo',
       'duplex', 'flat', 'cottage/cabin', 'in-law', 'loft', 'land',
       'assisted living'], dtype=object)

In [36]:
rental_listings.region.unique()

array(['birmingham', 'huntsville / decatur', 'dothan', 'mobile',
       'montgomery', 'florence / muscle shoals', 'gadsden-anniston',
       'tuscaloosa', 'anchorage / mat-su', 'fairbanks', 'phoenix',
       'flagstaff / sedona', 'tucson', 'little rock', 'prescott', 'yuma',
       'fayetteville', 'bakersfield', 'texarkana', 'fresno / madera',
       'hanford-corcoran', 'humboldt county', 'inland empire',
       'los angeles', 'kenai peninsula', 'southeast alaska',
       'mohave county', 'fort smith', 'jonesboro', 'show low',
       'gold country', 'sierra vista', 'chico', 'imperial county',
       'boulder', 'modesto', 'orange county', 'mendocino county',
       'merced', 'palm springs', 'reno / tahoe', 'monterey bay',
       'redding', 'sacramento', 'san diego', 'san luis obispo',
       'santa barbara', 'SF bay area', 'stockton', 'ventura county',
       'susanville', 'colorado springs', 'yuba-sutter', 'visalia-tulare',
       'siskiyou county', 'santa maria', 'denver', 'northwest C

In [37]:
rental_listings.parking_options.unique()

array(['street parking', 'off-street parking', nan, 'carport',
       'attached garage', 'detached garage', 'no parking',
       'valet parking'], dtype=object)

In [38]:
rental_listings.laundry_options.unique()

array(['laundry on site', 'w/d hookups', 'w/d in unit', nan,
       'laundry in bldg', 'no laundry on site'], dtype=object)

In [39]:
rental_listings.comes_furnished.unique()

array([0, 1])

In [42]:
rental_listings.cats_allowed.unique()

array([1, 0])

In [43]:
rental_listings.dogs_allowed.unique()

array([1, 0])

In [44]:
rental_listings.smoking_allowed.unique()

array([1, 0])

In [45]:
rental_listings.wheelchair_access.unique()

array([0, 1])

In [46]:
rental_listings.electric_vehicle_charge.unique()

array([0, 1])